//Generated by Kieu_Hong_Phong - B22DCKH084
#include <iostream>
using namespace std;
void sinh(int n, int a[], int &ok){
	int i=n-1;
	while(i>=0&&a[i]==1){
		i--;
	}
	if (i<0) ok=1;
	else{
		a[i]=1;
		for (int j=i+1;j<n;j++) a[j]=0;
	}
}
int main(){
	int n;
	cin>>n;
	int a[n];
	for (int i=0;i<n;i++) a[i]=0;
	int ok=0;
	while(!ok){
		for (int i=0;i<n;i++){
			cout<<a[i];
		}
		cout<<"\n";
		sinh(n,a,ok);
	}
}
