//Generated by Kieu_Hong_Phong - B22DCKH084
#include <iostream>
#include <algorithm>
using namespace std;
void sinh(int n, int a[], int &ok){
	int i=n-1;
	while (i>0 && a[i-1]>a[i]){
		i--;
	}
	if (i<=0) ok=1;
	else{
		int imin=i;
		for (int j=i;j<n;j++){
			if (a[imin]>a[j]&&a[j]>a[i-1]) imin=j;
		}
		swap(a[imin],a[i-1]);
		sort(a+i,a+n);
	}	
}
int main(){
	int n;
	cin>>n;
	int a[n];
	for (int i=0;i<n;i++) a[i]=i+1;
	int ok=0;
	while(!ok){
		for (int i=0;i<n;i++) cout<<a[i]<<" ";
		cout<<"\n";
		sinh(n,a,ok);
	}
}
/*
123 132 213

*/
