////Generated by Kieu_Hong_Phong - B22DCKH084
#include <iostream>
using namespace std;
void sinh(int n, int k, int a[], int &ok){
	int i=k-1;
	while(i>=0&&a[i]==n-k+i+1){
		i--;
	}
	if (i<0) ok=1;
	else{
		a[i]++;
		for (int j=i+1;j<k;j++) a[j]=a[j-1]+1;
	}
}
int main(){
	int n,k;
	cin>>n>>k;
	int a[k];
	for (int i=0;i<k;i++) a[i]=i+1;
	int ok=0;
	while(!ok){
		for (int i=0;i<k;i++) cout<<a[i]<<" ";
		cout<<"\n";
		sinh(n,k,a,ok);
	}
}
